# Generated by Django 5.2 on 2025-05-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='batch_id',
            new_name='batch',
        ),
    ]
